-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZB5iNyYhXxynr5ed
b+lgR+lmQxVsPz2OX8DvoadAyTWgCgYIKoZIzj0DAQehRANCAATESDMD2jXqQGEX
B2Pf15MkP7Wf01WfYRgtlTJ4mnmUpFDzGCUaUAoDs/ixSUGRxVoH7dCyuor7KZ6c
IO18Kzrm
-----END PRIVATE KEY-----